version: "3.8"
services:
  backend:
    build:
      context: ./nest-backend
    ports:
      - "3001:3001"
    networks:
      - app-network
  scraper:
    build:
      context: ./python-microservice
    ports:
      - "50051:50051"
    networks:
      - app-network

  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - scraper

networks:
  app-network:
    driver: bridge