version: "3.8"
services:
  backend:
    build:
      context: ./nest-backend
    ports:
      - "3001:3001"
    networks:
      - app-network
  scraper:
    build:
      context: ./python-microservice
    ports:
      - "50051:50051"
    networks:
      - app-network

  frontend:
    build: 
      context: ./react-frontend
      args:
        - VITE_BACKENDURL=http://backend:3001
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - scraper
    networks:
      - app-network
    environment:
      - VITE_BACKENDURL=http://backend:3001

networks:
  app-network:
    driver: bridge